version: "3.9"
services:
  web:
    build: .
    command: python /Bookstore/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/Bookstore
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-a(@c&@ku16r8tg7t9dhvuca^0#%2&8l$35orps1(2c6vaplltq"
      - "DJANGO_DEBUG=True"
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data: